# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: BridgeCode
description: # > means to ignore newlines until "baseurl:"
  Learn programming without quitting your day job! Take night and weekend coding classes in Gresham, Oregon. No experience required. Contact us now for more info!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Markdown settings
markdown: kramdown

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - package.json
  - README.md
  - CNAME
  # - assets/sass # this line placed here by default by jekyll. removing it allowed --watch for sass

# Plugin settings
plugins_dir:
  - jekyll-feed
  - jekyll-sitemap
